services:
  datamanager_api:
    build: .
    container_name: datamanager_server
    restart: always # Faz ele reiniciar sempre e ligar com o PC
    ports:
      - "8686:8686" # Porta do servidor (esquerda) mapeada pra porta do container (direita)
    volumes:
      - ./database:/app/database
    # Comando padrão para abrir a API
    command: [ "python", "network_server.py" ]
