services:
  datamanager_api:
    image: ghcr.io/guilsmatos1/datamanager:latest # Puxando do Github Registry
    container_name: datamanager_server
    environment:
      - DATAMANAGER_API_KEY=${DATAMANAGER_API_KEY:-YOUR_API_KEY_HERE} # Chave de API, defina no CasaOS
    restart: always # Faz ele reiniciar sempre e ligar com o PC
    ports:
      - "8686:8686" # Porta do servidor (esquerda) mapeada pra porta do container (direita)
    volumes:
      - ./database:/app/database
      - ./metadata:/app/metadata
    # Comando padrão para abrir a API
    command: [ "python", "network_server.py" ]
