version: '3.8'

services:
  datamanager:
    build: .
    container_name: datamanager
    # Mantém o container interativo
    stdin_open: true  # equivalente ao flag -i do docker run
    tty: true         # equivalente ao flag -t do docker run
    volumes:
      # Monta a pasta database local para persistir dados baixados
      - ./database:/app/database
