[project]
name = "trademachine-workspace"
version = "0.1.0"
description = "Monorepo para os projetos TradeMachine"
requires-python = ">=3.11"
dependencies = []

[tool.uv.workspace]
members = [
    "DataManager",
    "PortifolioMaster",
    "TradingMonitor",
    "BacktestEngine"
]

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "import-linter>=2.11",
    "deptry>=0.25.1",
    "pre-commit>=4.5.1",
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "W", "B", "UP", "S"]
ignore = ["E501", "S101", "S108", "S603"]

[tool.polylith]
namespace = "trademachine"

[tool.polylith.structure]
theme = "dark"

[tool.polylith.resources]
bases = "bases"
components = "components"

[tool.uv.sources]
trademachine = { workspace = true }

[tool.deptry]
exclude = ["DataManager", "PortifolioMaster", "TradingMonitor", "BacktestEngine", "venv", ".venv", "tests", ".*_cache"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
testpaths = [
    "DataManager/tests",
    "PortifolioMaster/tests",
    "TradingMonitor/tests"
]
pythonpath = [
    "DataManager/src",
    "PortifolioMaster/src",
    "TradingMonitor/src",
    "TradingMonitor"
]

[tool.mypy]
python_version = "3.12"
plugins = ["pydantic.mypy"]
warn_return_any = true
warn_unused_ignores = true
check_untyped_defs = true
no_implicit_optional = true
ignore_missing_imports = true
