"""Public API for the BacktestEngine component."""

from trademachine.backtestengine.config import BacktestConfig
from trademachine.backtestengine.engine import (
    BacktestEngine,
    BacktestResult,
    TradeExecutor,
    run_backtest,
)
from trademachine.backtestengine_broker.public import (
    BUY_ACTIONS,
    DEAL_TYPE_MAP,
    MT5_AVAILABLE,
    ORDER_TYPE_MAP,
    REQUIRED_TESTER_CONFIG_KEYS,
    SELL_ACTIONS,
    STRING2TIMEFRAME_MAP,
    SUPPORTED_TESTER_MODELLING,
    TIMEFRAME2STRING_MAP,
    AccountInfo,
    MarginEvent,
    MetaTrader5,
    PeriodSeconds,
    SnapshotExporters,
    SnapshotImporters,
    SymbolInfo,
    Tick,
    TradeDeal,
    TradeOrder,
    TradePosition,
    ensure_utc,
    evaluate_margin_state,
    make_tick,
    make_tick_from_dict,
    make_tick_from_tuple,
    month_bounds,
    no_mt5_runtime_error,
    snapshot_broker_data,
)
from trademachine.backtestengine_history.public import HistoryManager
from trademachine.backtestengine_stats.public import BacktestStats

__all__ = [
    "AccountInfo",
    "BUY_ACTIONS",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "BacktestStats",
    "DEAL_TYPE_MAP",
    "HistoryManager",
    "MT5_AVAILABLE",
    "MarginEvent",
    "MetaTrader5",
    "ORDER_TYPE_MAP",
    "PeriodSeconds",
    "REQUIRED_TESTER_CONFIG_KEYS",
    "SELL_ACTIONS",
    "STRING2TIMEFRAME_MAP",
    "SUPPORTED_TESTER_MODELLING",
    "SnapshotExporters",
    "SnapshotImporters",
    "SymbolInfo",
    "TIMEFRAME2STRING_MAP",
    "Tick",
    "TradeDeal",
    "TradeExecutor",
    "TradeOrder",
    "TradePosition",
    "ensure_utc",
    "evaluate_margin_state",
    "make_tick",
    "make_tick_from_dict",
    "make_tick_from_tuple",
    "month_bounds",
    "no_mt5_runtime_error",
    "run_backtest",
    "snapshot_broker_data",
]
