[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trademachine-backtestengine-history"
version = "0.1.0"
description = "Historical data access for BacktestEngine"
dependencies = [
    "polars>=1.39.3",
    "trademachine-backtestengine-broker",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["trademachine*"]
