[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trademachine-backtestengine-stats"
version = "0.1.0"
description = "Statistics for BacktestEngine"
dependencies = [
    "numpy>=2.4.3",
    "pandas>=2.2.3,<3.0.0",
    "trademachine-backtestengine-broker",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["trademachine*"]
