#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
BUNDLE_NAME="PortifolioMaster_Windows"
STAGING_DIR="$DIST_DIR/$BUNDLE_NAME"
ZIP_PATH="$DIST_DIR/${BUNDLE_NAME}.zip"

echo "Building standalone Windows bundle for PortifolioMaster..."
echo "Root: $ROOT_DIR"

rm -rf "$STAGING_DIR" "$ZIP_PATH"
mkdir -p "$STAGING_DIR/bases" "$STAGING_DIR/components"

cp -R "$ROOT_DIR/bases/portifolio_master_cli" "$STAGING_DIR/bases/"
cp -R "$ROOT_DIR/components/core" "$STAGING_DIR/components/"
cp -R "$ROOT_DIR/components/mt5" "$STAGING_DIR/components/"
cp -R "$ROOT_DIR/components/portifoliomaster" "$STAGING_DIR/components/"

rm -rf \
  "$STAGING_DIR/bases/portifolio_master_cli/test" \
  "$STAGING_DIR/components/core/test" \
  "$STAGING_DIR/components/mt5/test" \
  "$STAGING_DIR/components/portifoliomaster/test"

find "$STAGING_DIR" \( -name __pycache__ -o -name '*.egg-info' -o -name '.DS_Store' \) -prune -exec rm -rf {} +
find "$STAGING_DIR" -type d -empty -delete

cat > "$STAGING_DIR/pyproject.toml" <<'EOF'
[project]
name = "portifoliomaster-windows-bundle"
version = "0.1.0"
description = "Standalone workspace for PortifolioMaster on Windows"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "colorama>=0.4.6",
    "lxml>=6.0.2",
    "numpy>=2.4.3",
    "pandas>=2.2.3,<3.0.0",
    "plotly>=6.6.0",
    "polars>=1.39.3",
    "prompt-toolkit>=3.0.52",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "tqdm>=4.67.3",
    "typer>=0.24.1",
    "trademachine-core>=0.1.0",
    "trademachine-mt5>=0.1.0",
    "trademachine-portifoliomaster>=0.1.0",
    "trademachine-portifolio-master-cli>=0.1.0",
]

[tool.uv.workspace]
members = [
    "bases/portifolio_master_cli",
    "components/core",
    "components/mt5",
    "components/portifoliomaster",
]

[tool.uv.sources]
trademachine-core = { workspace = true }
trademachine-mt5 = { workspace = true }
trademachine-portifoliomaster = { workspace = true }
trademachine-portifolio-master-cli = { workspace = true }
EOF

cat > "$STAGING_DIR/README.md" <<'EOF'
# PortifolioMaster for Windows

Este pacote contem apenas o necessario para rodar o `PortifolioMaster` fora do monorepo principal.

## Requisitos

- Windows 10 ou 11
- Python 3.12 instalado
- `uv` instalado

Instalacao do `uv` no PowerShell:

```powershell
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

## Como usar

1. Extraia o `.zip`.
2. Abra o PowerShell dentro da pasta `PortifolioMaster_Windows`.
3. Instale o ambiente:

```powershell
uv sync
```

4. Valide o CLI:

```powershell
uv run portifoliomaster --help
```

## Fluxos comuns

Carregar relatorios MT5:

```powershell
uv run portifoliomaster load .\reports --workers 8 --list
```

Aplicar drawdown pairing:

```powershell
uv run portifoliomaster pairing --load .\reports --workers 8 --target 4000 --tick 0.1 --apply
```

Medir throughput do motor para uma janela de 10 minutos:

```powershell
uv run portifoliomaster benchmark --load .\reports --load-workers 8 --min 5 --max 5 --corr 0.3 --workers 8 --sample-seconds 5 --target-time 600
```

Rodar otimizacao greedy com 2 loops:

```powershell
uv run portifoliomaster optimize --greedy --greedy-loops 2 --min 5 --top 10 --corr 0.3 --rank RetDD --print --output .\run_greedy
```

## Arquivos importantes

- `pyproject.toml`: workspace standalone do PortifolioMaster
- `bases/portifolio_master_cli/`: CLI
- `components/core/`: utilitarios compartilhados
- `components/mt5/`: parser dos reports HTML do MT5
- `components/portifoliomaster/`: logica do projeto
- `run_portifoliomaster.bat`: atalho opcional para chamar o CLI

## Atalho opcional

Voce tambem pode executar:

```powershell
.\run_portifoliomaster.bat --help
```
EOF

cat > "$STAGING_DIR/run_portifoliomaster.bat" <<'EOF'
@echo off
uv run portifoliomaster %*
EOF

(
  cd "$DIST_DIR"
  zip -r "${BUNDLE_NAME}.zip" "$BUNDLE_NAME" >/dev/null
)

echo "Bundle created:"
echo "  Folder: $STAGING_DIR"
echo "  Zip:    $ZIP_PATH"
echo
echo "Note: uv.lock is not generated by this script. The target Windows machine"
echo "must run 'uv sync' with internet access on first use."
