[project]
name = "portifoliomaster-project"
version = "0.1.0"
description = "PortifolioMaster build project"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "numpy>=1.26.4",
    "pandas>=2.2.0",
    "plotly>=6.6.0",
    "polars>=1.39.2",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "tqdm>=4.67.3",
]

[tool.polylith.projects]
"trademachine/portifoliomaster" = "components"
"trademachine/portifolio_master_cli" = "bases"

[tool.uv.sources]
trademachine = { path = "../../components/portifoliomaster/src" }
trademachine_bases = { path = "../../bases/portifolio_master_cli/src" }
